branches:
  only:
    - develop
    - master

language: php

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction

env:
  global:
    - CC_TEST_REPORTER_ID=67c43c4b5f8800fd12efe789a49e0ee28527e51106a1d8923f2bbbe9282fc480
  matrix:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-lowest"

before_script:
  - composer self-update
  - composer install --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - phpunit --verbose

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

sudo: false
